# Generated by Django 5.0 on 2024-01-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userprofile_bio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='PostImage',
        ),
    ]
